version: 0.2
phases:
  pre_build:
    commands:
      #- echo TargetLambdaFunctionCode ${TargetLambdaFunctionCode}
      #- echo Branch ${Branch}
      #- echo SourceS3Bucket ${SourceS3Bucket}
      #- echo TemplatesS3Bucket ${TemplatesS3Bucket}
      - >
        echo '
        {
          {
            "Parameters" : {
              "TargetLambdaFunctionCode" : "${TargetLambdaFunctionCode}",
              "Branch": "${Branch}",
              "SourceS3Bucket" : "${SourceS3Bucket}",
              "TemplatesS3Bucket" : "${TemplatesS3Bucket}"
            }
          }
        }' > deployparameters.json 
      - cat deployparameters.json 
  build:
    commands:
      - zip -rj ${TargetLambdaFunctionCode} function/*
      - aws s3 cp ${TargetLambdaFunctionCode} s3://${SourceS3Bucket}/${Branch}/
      - sam package --template-file template.yml --s3-bucket ${SourceS3Bucket} --output-template-file packaged.yaml
      - cat packaged.yaml

artifacts:
  files:
    - "packaged.yaml"
    - "deployparameters.json"
  discard-paths: yes

#  install:
#    runtime-version:
#      nodejs: 10
#    commands:
#      - aws cloudformation package --template-file template.yaml --s3-bucket ${S3_BUCKET} --output-template-file outputTemplate.yaml

#artifacts:
#  type: zip
#  files:
#    - template.yaml
#    - outputTemplate.yaml