AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Cria o ambiente na AWS com
  1. Bucket S3 para o fonte do Lambda
  2. Policies e Roles
  3. (TODO) CodePipeline

  Executar os comandos abaixo no AWS CLI
  aws cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name fuzzy-doodle-environment --template-body file://createawsenvironment.yml --parameters ParameterKey=SourceS3Bucket,ParameterValue=fuzzy-doodle-source

Parameters:
  SourceS3Bucket:
    Type: String

Resources:
  SourceBucket:
   Type: AWS::S3::Bucket
   DeletionPolicy: Retain
   Properties:
      BucketName: !Sub ${SourceS3Bucket}
      VersioningConfiguration:
        Status: Enabled

  RoleFuzzyDoodle:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub RoleFuzzyDoodle
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
            - codedeploy.amazonaws.com
            - cloudformation.amazonaws.com
            - iam.amazonaws.com
            - s3.amazonaws.com
          Action:
            - 'sts:AssumeRole'

  PolicyFuzzyDoodle:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub PolicyFuzzyDoodle
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
            - 's3:PutObject'
            - 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${SourceS3Bucket}/*'
          - Effect: Allow
            Action:
            - 's3:CreateBucket'
            - 'codedeploy:CreateApplication'
            - 'codedeploy:DeleteApplication'
            - 'iam:CreateRole'
            - 'iam:DeleteRole'
            - 'iam:AttachRolePolicy'
            - 'iam:DetachRolePolicy'
            - 'iam:DeleteRolePolicy'
            - 'codedeploy:DeleteApplication'
            Resource: '*'
          - Effect: Allow
            Action:
            - "cloudformation:DescribeStacks"
            - "cloudformation:ListStackResources"
            - "cloudformation:CreateChangeSet"
            - "cloudwatch:ListMetrics"
            - "cloudwatch:GetMetricData"
            Resource: 
            - 'arn:aws:cloudformation:::stackfuzzy-doodle*'
            - 'arn:aws:cloudformation:*:aws:transform/Serverless*'
      Roles:
      - !Ref RoleFuzzyDoodle