AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'A serverless (AWS based) document generator based on templates

  '
Parameters:
  SOURCES3BUCKET:
    Type: String
  TEMPLATES_S3_BUCKET:
    Type: String
Resources:
  TemplatesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Fn::Sub: ${TEMPLATES_S3_BUCKET}
  DocGenerator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DocGenerator
      CodeUri:
        Fn::Sub: ${SOURCES3BUCKET}/${BRANCH}/${TARGET_LAMBDA_FUNCTION_CODE}
      Handler: doc-generator.app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          TemplatesS3Bucket:
            Fn::Sub: arn:aws:s3:${AWS::Region}:${AWS::AccountId}:${TEMPLATES_S3_BUCKET}
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Timeout: 60
      MemorySize: 512
      Policies:
      - LambdaInvokePolicy:
          FunctionName: DocGenerator
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: ${TEMPLATES_S3_BUCKET}
      Events:
        MyFunctionApi:
          Type: Api
          Properties:
            Path: /fuzzy-doodle
            Method: post
Outputs:
  DocGeneratorApi:
    Description: API Gateway endpoint URL for Prod stage for function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/doc-generator/
  HelloWorldFunction:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DocGenerator
      - Arn
