AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A serverless (AWS based) document generator based on templates

Parameters:
  TemplatesS3Bucket:
    Type: String
    #Description: blabla
    Default: fuzzy-doodle-templates
  SourceS3Bucket:
    Type: String
    Default: fuzzy-doodle-source
  Branch:
    Type: String
    Default: main
  TargetLambdaFunctionCode:
    Type: String
    Default: fuzzy-doodle.zip

Resources:
  TemplatesBucket:
   Type: AWS::S3::Bucket
   DeletionPolicy: Delete #Retain
   Properties:
     BucketName: !Sub ${TemplatesS3Bucket}

  DocGenerator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DocGenerator
      CodeUri: #!Sub s3://${SourceS3Bucket}/${Branch}/${TargetLambdaFunctionCode}
        Bucket: !Sub ${SourceS3Bucket}
        Key: !Sub ${Branch}/${TargetLambdaFunctionCode}
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          TemplatesS3Bucket: !Sub "${TemplatesS3Bucket}"
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Timeout: 60
      MemorySize: 512
      Policies:
        - LambdaInvokePolicy:
            FunctionName: DocGenerator
        - S3ReadPolicy:
            BucketName: !Sub "${TemplatesS3Bucket}"
      Events:
        MyFunctionApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /doc-generator
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DocGeneratorApi:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Branch}/doc-generator/"
  HelloWorldFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt DocGenerator.Arn